config/routes.rb
Rails.application.routes.draw do
  #root route
  root 'static_pages#home'

  #page routes for portfolio content
  get 'about'   => 'static_pages#about'
  get 'webdev'  => 'static_pages#webdev'
  get 'writing' => 'static_pages#writing'
  get 'contact' => 'static_pages#contact'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def webdev
  end

  def writing
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= yield(:title) %> | Portfolio </title>
  <%= stylesheet_link_tag    'application', media: 'all',
                             'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
        <div>
          <nav>
            <ul class="header">
              <li> <%= link_to "Home",     root_path %> </li>
              <li> <%= link_to "Web Dev",  webdev_path %> </li>
              <li> <%= link_to "Writing",  writing_path %> </li>
              <li> <%= link_to "About",    about_path %> </li>
              <li> <%= link_to "Contact",  contact_path %> </li>
            </ul>
          </nav>
        </div>
      </header>

      <%= yield %>

</body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

<h1>About Me</h1>
<p>
  I was born and raised in New York City, the son of two artists.
  After undergrad at Hartwick College, I taught English in Austria on a
  Fulbright Grant, got an LLM in International Law at the University of
  Edinburgh in Scotland, and went to law school at the University of Miami.
  After graduating law school and deciding that being a lawyer was not for me
  <a href=
    "http://leavelawbehind.com/2016/01/19/lessons-from-someone-who-just-left"
    target="_blank"> (at least for now),
  </a>
  I went to <a href="http://wyncode.co" target="_blank">Wyncode Academy</a>
  in Miami to learn how to be a web developer. I am currently
  building my startup TopOutlines.com and looking for a job
  programming, or in a related field. I live in Miami, Florida with my
  girlfriend Stephanie, and our dog Bridger. If you would like to contact
  me, I can be reached at KraemerWest@gmail.com.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>

<h1>StaticPages#contact</h1>
<p>Insert a form that goes to my email here</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>


<div id="Title">
  <h1>West Kraemer's Web Dev & Writing Portfolio</h1>
</div>

<div id="Message">
  <h2>Thoughful Design and Original Writing</h2>
</div>

<div class="Content">
    <div>
      <p>Writing Projects</p>
        <img src="assets/typewriter.jpg" alt="Typewriter", id="typewriter">
    </div>

    <div>
      <p>Web Dev Projects</p>
        <img src="assets/code.jpg" alt="Whiteboard", id="whiteboard">
    </div>

    <div>
      <p>About</p>
        <img src="assets/kraemer.jpg" alt="Me", id="kraemer">
    </div>

</div>

app/views/static_pages/webdev.html.erb
<% provide(:title, "Web Dev") %>

<h1>StaticPages#webdev</h1>
<p>Find me in app/views/static_pages/webdev.html.erb</p>

app/views/static_pages/writing.html.erb
<% provide(:title, "Writing") %>

<h1>StaticPages#writing</h1>
<p>Find me in app/views/static_pages/writing.html.erb</p>